scheduler:
    offset: 900000

mailgun:
    api-key: HIDDEN
    domain-name: HIDDEN.mailgun.org
    recipient: who-shall-get-your-mail@gmail.com

website:
    url: https://www.enteryour-url-here.com
    selector1: span.availability-indicator-success
    selector2: span.availability-indicator-warning
